### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no lpsolve55j in java.library.path

### ISSUE THREAD

**Issue by yasha-spare** [datumbox/lpsolve#2]
Thanks for putting this together!  However, I'm having a little trouble getting it working, it's throwing when I call `LpSolve.makeLp`.

```bash
(run-main-0) java.lang.UnsatisfiedLinkError: no lpsolve55j in java.library.path
java.lang.UnsatisfiedLinkError: no lpsolve55j in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
        at java.lang.Runtime.loadLibrary0(Runtime.java:871)
        at java.lang.System.loadLibrary(System.java:1124)
        at lpsolve.LpSolve.<clinit>(LpSolve.java:275)
        // etc
```

I think it depends on system libraries?  Would you be able to provide step-by-step instructions to get this working on Mac and Linux?

**Comment by datumbox** [comment]
Unfortunately Datumbox framework has long stopped using the specific dependency due to the licensing issues and the extra system binaries needed, so this repo is no longer maintained.
